In [6]:
import pandas as pd

# Read the original CSV file
data = pd.read_csv("filmtv_movies - ENG.csv", sep=",")

# Get the number of rows in the original DataFrame
num_rows_original = data.shape[0]

# Clean the DataFrame // drop all NaN rows 
df = data.dropna(subset=["actors", "title",])

# Get the number of rows in the cleaned DataFrame
num_rows_cleaned = df.shape[0]

# Filter out movies with only one actor
df = df[df['actors'].str.split(',').map(len) > 1]

# Keep only movies from the United States
df = df[df['country'] == 'United States']

# Retain only the title and actors columns
df = df.loc[:, ['title', 'actors']]

# Replace commas with semicolons in the actors column
df['actors'] = data['actors'].str.replace(',', ';')

# Save the cleaned DataFrame to a CSV file
df.to_csv('movie.csv', index=False)
df

,title,actors
2,Ride a Wild Pony,Michael Craig; John Meillon; Eva Griffith; Gra...
3,Diner,Mickey Rourke; Steve Guttenberg; Ellen Barkin;...
7,Dead-Bang,Don Johnson; Penelope Ann Miller; William Fors...
9,At Close Range,Christopher Walken; Sean Penn; Chris Penn; Mar...
11,Sleeping with the Enemy,Julia Roberts; Patrick Bergin; Kevin Anderson;...
...,...,...
40292,Agatha,Emily Joyce-Dial; Nathan Lewis; Lauren Mascali...
40295,The Christmas Thief,Michelle Borth; Jarrid Masse; Leigh Foster; Sa...
40296,One More Saturday Night,Tom Davis; Al Franken; Moira Sinise; Frank How...
40297,The Inside Outtakes - Bo Burnham,Bo Burnham; David The Spider; Unnamed Spider
40299,"Me, Natalie",Patty Duke; James Farentino; Martin Balsam; Al...